# Generated by Django 5.2.3 on 2025-06-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visuals', models.FloatField(verbose_name='visuals')),
                ('acting', models.FloatField(verbose_name='acting')),
                ('thought_provoking', models.FloatField(verbose_name='meaning')),
                ('dialog', models.FloatField(verbose_name='dialogue')),
                ('makes_me_cry', models.FloatField(verbose_name='crying')),
                ('genre_execution', models.FloatField(verbose_name='genre')),
                ('rewatchability', models.FloatField(verbose_name='rewatch')),
                ('fun_to_watch', models.FloatField(verbose_name='fun_to_watch')),
                ('average', models.FloatField(blank=True, null=True)),
                ('recommend', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'To someone who likes the genre')], max_length=128, null=True)),
                ('movie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_ratings.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
