# Generated by Django 5.2.1 on 2025-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
