# Generated by Django 5.2.4 on 2025-09-24 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_ratings', '0003_alter_movie_tmdb_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('movie_title', 'user'), name='unique_user_review_per_movie'),
        ),
    ]
